version: "3"

services:
  server:
    build: ./server/
    depends_on:
      redis:
        condition: service_healthy
    container_name: python_server

  redis:
    image: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli"]
      interval: 5s
      timeout: 5s
      retries: 5

  client:
    build: ./client/
    depends_on:
      redis:
        condition: service_healthy
    container_name: python_client
